### ISSUE TITLE
How to properly install?

### ISSUE THREAD

**Issue by Trainmaster9977** [reframedultimate/ReFramed#101]
Hello! I'm someone currently trying to start my journey into looking at replays, and stumbled across this, thinking _perfect, this is exactly the kind of thing I can probably learn a lot from or even use!_ So I looked at the install instructions, which confused me, but I tried anyways. 

Cloned this repo, CD' into it's folder (which was reframed instead of ultimate hindsight), made the build folder then CD' into that, set the path variable, and theeeen I ran into issues. I am in fact working on windows for the record.

first was cmake -A x64 -DCMAKE_BUILD_TYPE=<Debug|Release> -DCMAKE_INSTALL_PREFIX:PATH="path\to\install\dir" -DCMAKE_CXX_FLAGS="/MP" ..\

I chose release for obvious reasons, and decided to make a folder just titled "A" (without quotes) to serve as the path. Since I had no clue what else I should do. I then ran the command with that put as the install directory, and it seemed to work at first, before throwing up tons of errors, resulting finally in

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

I at least gave the next command of cmake --build . --config <Debug|Release> --target install a shot, but it just resulted in

MSBUILD : error MSB1009: Project file does not exist.
Switch: inst.vcxproj

I really want to test out this tool if I can!! This seems like the exact sort of thing I'm looking for, but I'm just not sure how to properly install it.

So more detailed instructions would be appreciated.

Thanks!!!!

**Comment by TheComet** [comment]
Hi and welcome!

There are prebuilt executables you can download for Windows in the releases section here: [https://github.com/reframedultimate/ReFramed/releases](https://github.com/reframedultimate/ReFramed/releases)

That's the easiest way to get started on Windows.

Building it requires you to install some dependencies first. Did you install Qt?

**Comment by Trainmaster9977** [comment]
Just tried to install Qt, and now it's asking for a company email and stuff....which is not exactly what I expected and I assume there's an easier way to use this?

Also sorry, didn't notice the release! Github puts the release stuff in a really odd place in my opinion, which makes me never notice it. My bad!

Also, maybe it's due to not installing the thing, when I try to use the application to open a replay file (.bin), it just doesn't recognize it.
